settings:
  accountName: "Example"
  deploymentUid: "ss123456"
  sitecorePrefix: "sitecore"
  pathToWWWRoot: "C:\\inetpub\\wwwroot"
  solrUsername: ""
  solrPassword: ""
  sitecoreVersion : "10.0.0"               # Supported versions - 9.0.2, 9.1.1, 9.2.0 and 9.3.0
  isUniqueConfigs: "true"                 # [true/false] 
  configurationMode: "XP|XCONNECT|COMMERCE"         # ["XP" "XCONNECT" "COMMERCE" "XP|XCONNECT|COMMERCE"]
  isAzurePaaS: "true"
  Commerce:
    CommerceServicesPostfix: "Sc9"
    isXCSwitchOnRebuild: "false"