settings:
  accountName: "SilverQAAccount"
  deploymentUid: "ss550096"
  sitecorePrefix: "site92"
  pathToWWWRoot: "C:\\inetpub\\wwwroot"
  solrUsername: ""
  solrPassword: ""
  sitecoreVersion : "9.2.0"               # Supported versions - 9.0.2, 9.1.1, 9.2.0 and 9.3.0
  isUniqueConfigs: "true"                 # [true/false] 
  configurationMode: "XP|XCONNECT|COMMERCE"         # ["XP" "XCONNECT" "COMMERCE" "XP|XCONNECT|COMMERCE"]
  commerce:
    commerceServicesPostfix: "Sc9"
    isXCSwitchOnRebuild: "false"