settings:
  accountName: "MyAccountName"
  deploymentUid: "ss881269"
  sitecorePrefix: "demo"
  pathToWWWRoot: "C:\\inetpub\\wwwroot"
  solrUsername: ""
  solrPassword: ""
  sitecoreVersion : "9.0.2" #Supported versions - 9.0.2 and 9.1.1