settings:
  accountName: "MyAccountName"
  deploymentUid: "ss881269"
  sitecorePrefix: "demo"
  pathToWWWRoot: "C:\\inetpub\\wwwroot"
  solrUsername: ""
  solrPassword: ""
  sitecoreVersion : "9.3.0" #Supported versions - 9.0.2, 9.1.1, 9.2.0 and 9.3.0